config/routes.rb
TodoApp::Application.routes.draw do
  
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  resources :sessions, only: :create
  resources :users, except: :new

  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  
  resources :lists do
    collection do
      get 'finished'
      get 'unfinished'
    end
    
    resources :todos
  end
  

  root :to => 'static_pages#home'

end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :name
  
  has_many :todos
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :authorize
  layout 'with_links'
  
  # GET /lists
  # GET /lists.json
  def index
    @lists = List.paginate(page: params[:page], per_page: 10)
    @title = "All Lists"
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end
  
  def finished
    @lists = List.paginate(page: params[:page], per_page: 5)
    @title = "Finished Lists"
    respond_to do |format|
      format.html {
        render 'index'
      }
      format.json { render json: @lists}
    end
  end
  
  def unfinished
    @lists = List.paginate(page: params[:page], per_page: 5)
    @title = "Unfinished Lists"
    respond_to do |format|
      format.html { render 'index'}
      format.json { render json: @lists}
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = List.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    @list = List.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(params[:list])

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render json: @list, status: :created, location: @list }
      else
        format.html { render action: "new" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= simple_form_for @list, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                lists_path, :class => 'btn' %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<%- model_class = @list.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/lists/index.html.erb
<%- model_class = List.new.class -%>
<h1><%= @title %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= link_to list.id, list_path(list) %></td>
        <td><%= list.name %></td>
        <td><%=l list.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_list_path(list), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      list_path(list),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_list_path,
            :class => 'btn btn-primary' %>

app/views/lists/new.html.erb
<%- model_class = @list.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/lists/show.html.erb
<%- model_class = @list.class -%>
<ul class="breadcrumb">
  <li>
    <%= link_to 'My Lists', lists_path() %>
    <span class="divider">/</span>
  </li>
  <li>
    <%= link_to 'Edit This List', list_todos_path(@list) %>
    <span class="divider">/</span>
  </li>
  <li class="active">
    <a href="#">Current List</a>
  </li>
</ul>

<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @list.name %></dd>
</dl>

<h2>Todo items</h2>
<%= render @list.todos %>

<h2>Add todo items</h2>
<%= render "todos/form"%>