config/routes.rb
TodoApp::Application.routes.draw do
  
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  resources :sessions, only: :create
  resources :users, except: :new

  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  
  resources :lists do
    collection do
      get 'finished'
      get 'unfinished'
    end
    
    resources :todos
  end
  

  root :to => 'static_pages#home'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  attr_accessible :item, :completed
  after_initialize :default_values
  
  validates :item, presence: true
  belongs_to :list
  
  private
    def default_values
      self.completed ||= false
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_filter :authorize
  layout 'with_links'
  
  # GET /todos
  # GET /todos.json
  def index
    @list = List.find(params[:list_id])
    @todos = @list.todos.paginate(page: params[:page], per_page: 5)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @list }
    end
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
    @list = List.find(params[:list_id])
    @todo = @list.todos.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list }
    end
  end

  # GET /todos/new
  # GET /todos/new.json
  def new
    @list = List.find(params[:list_id])
    @todo = @list.todos.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @todo }
    end
  end

  # GET /todos/1/edit
  def edit
    @list = List.find(params[:list_id])
    @todo = @list.todos.find(params[:id])
  end

  # POST /todos
  # POST /todos.json
  def create
    @list = List.find(params[:list_id])
    @todo = @list.todos.build(params[:todo])
    
    respond_to do |format|
      if @todo.save
        format.html { redirect_to list_todos_path(@list), notice: 'Todo item was successfully created.' }
        format.json { render json: @list, status: :created, location: @list }
      else
        format.html { render action: "new" }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /todos/1
  # PUT /todos/1.json
  def update
    @list = List.find(params[:list_id])
    @todo = @list.todos.find(params[:id])

    respond_to do |format|
      if @todo.update_attributes(params[:todo])
        format.html { redirect_to list_todo_url(@list, @todo), notice: 'Todo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to todos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/_form.html.erb
<%= simple_form_for [@list, if @todo.nil? then @list.todos.build else @todo end], :html => { :class => 'form-horizontal' } do |f| %>

  <%= f.input :item, input_html: {class: "span6", rows: 3}  %>
  <%= f.input :completed%>

  <div class="form-actions">
    <%= f.submit 'Save', :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                lists_path, :class => 'btn' %>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<%- model_class = todo.class -%>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:item) %>:</strong></dt>
  <dd><%= markdown todo.item %></dd>
  <dt><strong><%= model_class.human_attribute_name(:completed) %>:</strong></dt>
  <dd><%= check_box_tag :completed, todo.completed.to_s, todo.completed, disabled: true %></dd>
</dl>

app/views/todos/edit.html.erb
<%- model_class = @todo.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/todos/index.html.erb
<%- model_class = Todo.new.class -%>
<ul class="breadcrumb">
  <li>
    <%= link_to 'My Lists', lists_path() %>
    <span class="divider">/</span>
  </li>
  <li>
    <%= link_to 'View This List', list_path(@list) %>
    <span class="divider">/</span>
  </li>
  <li class="active">
    <a href="#">Current List</a>
  </li>
</ul>

<h1><%= @list.name %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:item) %></th>
      <th><%= model_class.human_attribute_name(:completed) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @list.todos.each do |todo| %>
      <tr>
        <td><%= link_to todo.id, list_todo_path(@list, todo) %></td>
        <td><%= markdown todo.item %></td>
        <td><%= check_box_tag :completed, todo.completed.to_s,  todo.completed, disabled: true %></td>
        <td><%=l todo.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_list_todo_path(@list, todo), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      list_todo_path(@list, todo),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= will_paginate %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_list_todo_path,
            :class => 'btn btn-primary' %>

app/views/todos/new.html.erb
<%- model_class = @todo.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/todos/show.html.erb
<%- model_class = @todo.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:item) %>:</strong></dt>
  <dd><%= markdown @todo.item %></dd>
  <dt><strong><%= model_class.human_attribute_name(:completed) %>:</strong></dt>
  <dd><%= @todo.completed %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              list_todos_path(@list), :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_list_todo_path(@list, @todo), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              list_todo_path(@list, @todo),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>