config/routes.rb
TodoApp::Application.routes.draw do
  
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  resources :sessions, only: :create
  resources :users, except: :new

  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  
  resources :lists do
    collection do
      get 'finished'
      get 'unfinished'
    end
    
    resources :todos
  end
  

  root :to => 'static_pages#home'

end

app/views/layouts/_head.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><%= content_for?(:title) ? yield(:title) : "Markdown Todo" %></title>
<%= csrf_meta_tags %>

<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
<![endif]-->

<%= stylesheet_link_tag "application", :media => "all" %>

<link href="images/favicon.ico" rel="shortcut icon">
<link href="images/apple-touch-icon.png" rel="apple-touch-icon">
<link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
<link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "Markdown Todo", root_path, class: "brand" %>
      <div class="container nav-collapse">
        <ul class="nav">
          <li><%= link_to("Home", root_path) %></li>
          <li><%= link_to("About me", about_path) %></li>
          <li><%= link_to("Blog", "http://pnhoang.tumblr.com") %></li>
          
          <% if current_user %>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user)%></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Sign out", signout_path, method: :delete %>
              </li>
            </ul>
          </li>
          <% else %>
            <li> <%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/_links.html.erb
<div class="well sidebar-nav">
  <h3>LINKS</h3>
  <ul class="nav nav-list">
    <li class="nav-header">Lists</li>
    <li><%= link_to(lists_path) do  %>
      <i class="icon-list"></i>
      My Lists
      <% end %>
    </li>
    <li><%= link_to (finished_lists_path)  do %>
      <i class="icon-check"></i>
      Finished Lists
      <% end %>
    </li>

    <li><%= link_to (unfinished_lists_path) do  %>
      <i class="icon-edit"></i>
      Unfinished Lists
      <% end %>
    </li>
    <li class="nav-header">Account</li>

    <% if current_user %>
    <li><%= link_to ("/path4") do %>
      <i class="icon-user"></i>
      My Account
      <% end %>
    </li>                  
    <li><%= link_to "Log Out", signout_path, method: :delete %></li>
    <% else %>
    <li><%= link_to "Sign Up", signup_path %></li>
    <li><%= link_to "Log In", signin_path %></li>
    <% end %>

  </ul>
</div><!--/.well -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= render 'layouts/head' %>
  </head>
  <body>

    <%= render 'layouts/header' %>

    <div class="container">
      <div class="content">
        <% flash.each do |name, msg| %>
          <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
            <a class="close" data-dismiss="alert" href="#">x</a>
            <%= msg %>
          </div>
        <% end %>
        
        <%= content_for?(:divided_spans) ? yield(:divided_spans) : yield %>
        
      </div><!--/content-->

      <footer class="footer">
        <p>&copy; MARKDOWN TODO 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/with_links.html.erb
<% content_for :divided_spans do %>
<div class="row">
  <div class="span9">
    <%= yield %>
  </div>
  <div class="span3">
    <%= render "layouts/links"%>
  </div>
</div>
<% end %>

<%= render template: 'layouts/application'%>